import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {backgroundColor: '#3366FF'},
  form: {
    borderColor: '#FFFFFF',
    borderWidth: 1,
    marginVertical: 30,
    marginHorizontal: 30,
    borderRadius: 10,
    color: '#FFFFFF',
    paddingHorizontal: 10,
  },
  dateContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    backgroundColor: '#222B45',
    borderTopEndRadius: 25,
    borderTopStartRadius: 25,
    paddingTop: 25,
    paddingBottom: 50,
    height: 700,
  },
  dateText: {
    color: 'white',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 5,
  },
  eventContainer: {
    backgroundColor: '#FCFCFC',
    borderTopEndRadius: 25,
    borderTopStartRadius: 25,
    paddingVertical: 25,
    paddingHorizontal: 20,
    position: 'absolute',
    width: '100%',
    top: 225,
    flexDirection: 'column',
  },
  eventTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FCFCFC',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000',
    marginTop: 20,
    letterSpacing: 2,
  },
  sliderBox: {
    borderRadius: 10,
    padding: 10,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    elevation: 5,
  },
  discoverContainer: {
    flexDirection: 'row',
    marginVertical: 15,
  },
  discoverBoxButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 50,
    padding: 10,
    marginRight: 20,
    marginLeft: 5,
    marginBottom: 10,
    shadowColor: '#000',
    elevation: 5,
    height: 50,
    width: 125,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  discoverButtonText1: {
    color: '#884DFF',
    marginLeft: 10,
  },
  discoverButtonText2: {
    color: '#FF3D71',
    marginLeft: 10,
  },
  discoverButtonText3: {
    marginLeft: 10,
  },
});
